### ISSUE TITLE
报错 error

### ISSUE THREAD

**Issue by lianfeng30** [az0ne/AZScanner#4]
File "/Users/AZscanner/web/web/trace.py", line 41, in trace

                            time.sleep(0.3)

            except:

                    pass

            reload(sys)

            sys.setdefaultencoding('utf-8')

            return render_template("trace.html", target = target,target_urllist=target_urllist,iplist=iplist,collect_dirs=collect_dirs,collect_ports=collect_ports,subdomain=subdomain)

            #return render_template("trace.html")

    UnboundLocalError: local variable 'target_urllist' referenced before assignment

**Comment by Tyomcat** [comment]
你好，这个报错怎么解决呢？
UnboundLocalError: local variable 'target_urllist' referenced before assignment

File "/Users/tyomcat/hack/AZScanner/AZscanner/web/web/trace.py", line 41, in trace
return render_template("trace.html", target = target,target_urllist=target_urllist,iplist=iplist,collect_dirs=collect_dirs,collect_ports=collect_ports,subdomain=subdomain)

**Comment by lianfeng30** [comment]
http://www.ww.com/
