### ISSUE TITLE
git clone失败

### ISSUE THREAD

**Issue by 9tail123** [az0ne/AZScanner#9]
root@localhost:~# git clone https://github.com/az0ne/AZScanner
正克隆到 'AZScanner'...
remote: Counting objects: 16, done.
^Cpacking objects:  68% (11/16)
root@localhost:~# git clone https://github.com/az0ne/AZScanner
正克隆到 'AZScanner'...
remote: Counting objects: 16, done.
remote: Total 16 (delta 0), reused 0 (delta 0), pack-reused 16
error: file write error (???????)
fatal: unable to write sha1 file
fatal: unpack-objects failed

**Comment by last2win** [comment]
一种可能是空间不足，还一种可能是权限不足，你用管理员权限试试。
